### ISSUE TITLE
Reconfigure `resyncPeriod`

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/cert-operator#49]
We reverted this value in #48, but having a timeout actually makes sense.

The CoreOS people say they usually set it to 10 minutes, FWIW.

**Comment by rossf7** [comment]
@asymmetric thanks for raising and totally agree we need a value for this. 0 is just wrong for a production operator.

The problem is the value to use as it varies a lot, including at CoreOS! ;) The Prometheus operator and Traefik use 5 minutes but the Rook operator uses 15 seconds. How about 1 minute? 

@xh3b4sd WDYT?

https://github.com/coreos/prometheus-operator/search?utf8=%E2%9C%93&q=resyncPeriod&type=
https://github.com/containous/traefik/search?utf8=%E2%9C%93&q=resyncPeriod&type=
https://github.com/rook/rook/search?utf8=%E2%9C%93&q=resyncPeriod&type=

**Comment by xh3b4sd** [comment]
I don't know. We have to try it out and test what works for us.
